{{define "content"}}
<table class="content-table">
    <thead>
        <tr>
            <th>Lp.</th>
            <th>Imie</th>
            <th>Nazwisko</th>
            <th>Data urodzenia</th>
            <th>Wydział</th>
            <th>Plec</th>
            <th>Usuń</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Marek</td>
            <td>Kowalski</td>
            <td>2001-12-03</td>
            <td>Informatyk</td>
            <td>Mężczyzna</td>
            <td><button>USUŃ</button></td>
        </tr>
        <tr>
            <td>2</td>
            <td>Marek</td>
            <td>Kowalski</td>
            <td>2001-12-03</td>
            <td>Informatyk</td>
            <td>Mężczyzna</td>
            <td><button>USUŃ</button></td>
        </tr>
        <tr>
            <td>3</td>
            <td>Marek</td>
            <td>Kowalski</td>
            <td>2001-12-03</td>
            <td>Informatyk</td>
            <td>Mężczyzna</td>
            <td><button>USUŃ</button></td>
        </tr>
        <tr>
            <td>4</td>
            <td>Marek</td>
            <td>Kowalski</td>
            <td>2001-12-03</td>
            <td>Informatyk</td>
            <td>Mężczyzna</td>
            <td><button>USUŃ</button></td>
        </tr>
    </tbody>
</table>
{{end}}